theme: jekyll-theme-minimal
title: Ryan Rose
description: A personal website.
exclude:
  - .github/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
url: "https://www.ryanrose.me" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
