theme: jekyll-theme-minimal
title: Ryan Rose
description: Ryan's personal website.
exclude: LICENSE
url: "https://www.ryanrose.me" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
