# https://github.com/marketplace/actions/deploy-pr-preview
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev
          export GEM_HOME="$HOME/gems"
          gem install bundler
          export PATH="$HOME/gems/bin:$PATH"
          bundle install
          bundle exec jekyll build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site # `bundle exec jekyll build` deposits it here
          preview-branch: main # branch deployed for Github pages
          custom-url: ryanrose.me # use custom domain name for preview link
          umbrella-dir: pr-preview # path following custom URL (e.g. ryanrose.me/pr-preview/...)
